---
title: "Times Series Modelling"
author: "Benjamin Würmli, Murat Kayhan und Velican Kaya"
author-title: "Autoren"
published-title: "Veröffentlicht"
date: last-modified
date-format: "DD.MM.YYYY"
title-block-banner: "#003366"
format: 
   html:
     toc: true
     toc-location: left
     toc-title: "Inhaltsverzeichnis"
     theme: cosmo
     embed-resources: true
     page-layout: full

knitr: 
  opts_chunk: 
    echo: false
    message: false
    warning: false
css: styling.css
---

```{r}

#notwendige libraries

library(ggthemes)
library(quantmod)
library(kableExtra)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(kableExtra)


```

## Übersicht


## Fragestellung


## Datenwrangling
```{r}

invisible(getSymbols("FEDFUNDS", src = "FRED"))
fed_funds_df <- data.frame(date = index(FEDFUNDS), rate = coredata(FEDFUNDS))

daten <- fed_funds_df %>%
  rename(rate = FEDFUNDS) %>% 
  mutate(change_rate = rate/lag(rate),
         change_difference = rate - lag(rate)) %>% 
  mutate(across(where(is.numeric),~round(.x,2)))

#deskriptive Statistik
desk_daten <- daten %>% 
  summarise(min_rate = min(rate),
            mean_rate = mean(rate),
            max_rate = max(rate)) %>% 
  mutate(across(where(is.numeric),~round(.x,2)))%>% 
  kbl(caption = "Deskriptive Statisitik der Zinsen",
      col.names = c("Minimum","Durschnitt","Maximum"),
      align = "cccc",
      escape = FALSE) %>% 
  kable_classic_2(full_width = FALSE)
  
  

desk_daten
head(daten)



# Plots:

ggplot(daten,aes(x = date,
                 y = FEDFUNDS))+
  geom_line()+
  theme_economist()+
  labs(title="Zinssätze der US-Notenbank:",
       caption = "Quelle: Board of Governors of the Federal Reserve System (US)",
       x = "Jahr",
       y = "Zinssatz")+
  theme(plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "darkblue"))

ggplot(daten,aes(x = date,
                 y = change_difference))+
  geom_line()+
  theme_economist()+
  labs(title="Änderungsdifferenz der Zinssätze der US-Notenbank",
       caption = "Quelle: Board of Governors of the Federal Reserve System (US)",
       x = "Jahr",
       y = "Änderungsdifferenz (%)") 

```



## Times Series Modelling


## Analysen


## Diskussion



## Referenzen
::: {#refs}
:::
